/*
 * @file
 * @brief freewebcamera adapter of the vendored net80211 library.
 *
 * The library (third-party/net80211) is OS-agnostic: this adapter
 * binds it to the image's CMSIS-RTOS2 surface. It carries the pieces
 * the embox lane keeps in its own build: the chip driver registry,
 * the interface table, the usbdi shim's worker threads, the heap
 * binding behind the library's weak allocation hooks, the firmware
 * registry and the lifecycle hook the app calls before usb_start().
 *
 * Claim model: usbh_urtwn_class.c (library) registers a CherryUSB
 * class hook, so a matched adapter attaches on the hub thread during
 * enumeration - which is why wlan_start() has to run before
 * usb_start() (the OSAL primitives and the firmware table must exist
 * by then). The lwIP netif is registered lazily afterwards, once the
 * TCP/IP thread is up.
 *
 * @author zhugengyu
 * @date 22.09.2026
 */

#include <stddef.h>
#include <stdint.h>

#include "cmsis_os2.h"

#include "wlan.h"

#include <port/port.h>
#include <port/osal/wlan_port_core.h>
#include <port/osal/cmsis_rtos2/wlan_port_cmsis.h>
#include <port/net/lwip/lwip_netif.h>

/* the compiled-in chip drivers (driver/urtwn/urtwn_reg.c exports it;
 * iwm waits for the PCIe backend, M5) */
extern const struct wlan_chip_driver urtwn_driver;
const struct wlan_chip_driver *const wlan_chip_drivers[] = {
	&urtwn_driver,
	NULL
};

/* the interface table the registry TUs and the usbdi shim share */
struct wlan_port_iface *wlan_port_ifs[WLAN_PORT_MAX_IF];
int wlan_port_if_n;

/* ------------------------------------------------------------------ */
/* heap binding (both kernel lines expose the heap_4 API shape: the
 * FreeRTOS line runs ucHeap, the ThreadX line the adapter's static
 * heap) - overrides the OSAL's weak malloc/free defaults */

extern void *pvPortMalloc(size_t length);
extern void vPortFree(void *ptr);

void *wlan_osal_alloc(size_t size) {
	return pvPortMalloc(size);
}

void wlan_osal_free(void *p) {
	vPortFree(p);
}

/* ------------------------------------------------------------------ */
/* usbdi shim worker threads (embox lane: net_bridge.c) */

void *wlan_port_thread_create(void *(*run)(void *), void *arg) {
	/* 16 KiB: the shim's worker loops are flat; the FreeRTOS demo
	 * lane ran the same loops on a 12 KiB stack */
	osThreadAttr_t attr = { "wlanwork", 0, NULL, 0, NULL,
				16 * 1024, osPriorityNormal, 0, 0 };

	/* the CMSIS thread starts running immediately; the embox lane
	 * needed a suspended-create + launch pair, this one does not */
	return (void *) osThreadNew((osThreadFunc_t) run, arg, &attr);
}

void wlan_port_thread_start(void *thread) {
	/* osThreadNew already runs the thread; the embox lane needed a
	 * suspended-create + launch pair, the CMSIS one does not */
	(void) thread;
}

/* ------------------------------------------------------------------ */
/* firmware: the urtwn blob embedded at build time (generated by the
 * library's scripts/gen_firmware_array.py) */

extern const uint8_t rtl8188eufw_data[];
extern const size_t rtl8188eufw_size;

/* ------------------------------------------------------------------ */

static int wlan_started;

int wlan_start(void) {
	if (wlan_started) {
		return 0;
	}
	wlan_osal_cmsis_init();
	if (wlan_port_firmware_register("rtl8188eufw.bin", rtl8188eufw_data,
		(size_t) rtl8188eufw_size) != 0) {
		return -1;
	}
	wlan_started = 1;
	return 0;
}

/* The lwIP presentation (rx hooks + netif) needs the TCP/IP thread,
 * so it cannot happen inside wlan_start() - by then tcpip_init has
 * not run. Registered lazily: the first caller after net_start()
 * wins, everyone else no-ops. */
int wlan_lwip_start(void) {
	static int lwip_done;
	static int lwip_tried;

	if (lwip_done) {
		return 0;
	}
	if (lwip_tried) {
		return -1;
	}
	lwip_tried = 1;
	if (wlan_lwip_init() != 0) {
		return -1;
	}
	lwip_done = 1;
	return 0;
}
