/*
 * @file
 * @brief freewebcamera adapter of the vendored net80211 library.
 *
 * The library (third-party/net80211) is OS-agnostic: this adapter
 * binds it to the image's CMSIS-RTOS2 surface. It carries the pieces
 * the embox lane keeps in its own build: the chip driver registry,
 * the interface table, the usbdi shim's worker threads, the heap
 * binding behind the library's weak allocation hooks, the firmware
 * registry and the lifecycle hook the app calls before usb_start().
 *
 * Claim model: usbh_urtwn_class.c (library) registers a CherryUSB
 * class hook, so a matched adapter attaches on the hub thread during
 * enumeration - which is why wlan_start() has to run before
 * usb_start() (the OSAL primitives and the firmware table must exist
 * by then). The lwIP netif is registered lazily afterwards, once the
 * TCP/IP thread is up.
 *
 * @author zhugengyu
 * @date 22.09.2026
 */

#include <stddef.h>
#include <stdint.h>

#include "cmsis_os2.h"

#include <usb_osal.h>
#include "usb_config.h"

#include "wlan.h"

#include "board.h"

#include <port/port.h>
#include <port/osal/wlan_port_core.h>
#include <port/osal/cmsis_rtos2/wlan_port_cmsis.h>
#include <port/net/lwip/lwip_netif.h>

/* the compiled-in chip drivers (driver/urtwn/urtwn_reg.c and
 * driver/rtw8189f/rtw8189f_reg.c export them; iwm waits for the PCIe
 * backend, M5) */
extern const struct wlan_chip_driver urtwn_driver;
extern const struct wlan_chip_driver rtw8189f_driver;
const struct wlan_chip_driver *const wlan_chip_drivers[] = {
	&urtwn_driver,
	&rtw8189f_driver,
	NULL
};

/* the interface table the registry TUs and the usbdi shim share */
struct wlan_port_iface *wlan_port_ifs[WLAN_PORT_MAX_IF];
int wlan_port_if_n;

/* ------------------------------------------------------------------ */
/* heap binding (both kernel lines expose the heap_4 API shape: the
 * FreeRTOS line runs ucHeap, the ThreadX line the adapter's static
 * heap) - overrides the OSAL's weak malloc/free defaults */

extern void *pvPortMalloc(size_t length);
extern void vPortFree(void *ptr);

void *wlan_osal_alloc(size_t size) {
	return pvPortMalloc(size);
}

void wlan_osal_free(void *p) {
	/* (the per-free trace that hunted the M7 wild write is gone now that
	 * the heap is TLSF - it flooded the console at rx rates) */
	vPortFree(p);
}

/* ------------------------------------------------------------------ */
/* usbdi shim worker threads (embox lane: net_bridge.c) */

/* The workers are created through the CherryUSB osal, NOT osThreadNew:
 * wlan_usbdi_attach runs on the USB hub thread - a raw ThreadX thread
 * created by usb_osal_thread_create itself - and the CMSIS-RTOS2 layer
 * is not safe to re-enter from there (M7 first boot: two cmsis-thr
 * threads died jumping to NULL right at the osThreadNew pair). Same
 * world, proven primitives.
 *
 * Worker urgency must land the workers BELOW the TCP/IP thread, or a
 * driver work segment (rx_drain through ieee80211_input and the
 * net80211 state machine) preempts tcpip mid-burst and the mailbox
 * fills (M11 r4: at ThreadX 5 vs tcpip 15 one 600 s downlink racked
 * up 1799 TCPIP_MSG_INPKT drops). The two osal backends consume the
 * number differently, so resolve it per kernel here:
 *   - ThreadX passes it raw to tx_thread_create (0 = most urgent):
 *     tcpip ends at 15 and the shell at 19, so 16 parks the workers
 *     between them. The old fixed 5 sat TEN levels above tcpip - the
 *     "below tcpip" comment it carried described only the FreeRTOS
 *     mapping and was backwards on this line.
 *   - FreeRTOS inverts it (configMAX_PRIORITIES - 1 - prio, 8 levels
 *     in the product image): 5 lands at 2, below tcpip's 4. Kept. */
#ifdef THREADX_BUILD
#define WLAN_WORK_PRIORITY	16
#else
#define WLAN_WORK_PRIORITY	5
#endif

void *wlan_port_thread_create(void *(*run)(void *), void *arg) {
	return usb_osal_thread_create("wlan-work",
				      CONFIG_USBHOST_PSC_STACKSIZE / 2,
				      WLAN_WORK_PRIORITY,
				      (usb_thread_entry_t) run, arg);
}

void wlan_port_thread_start(void *thread) {
	/* usb_osal_thread_create auto-starts (TX_AUTO_START); the embox
	 * lane needed a suspended-create + launch pair, this one does
	 * not. */
	(void) thread;
}

/* ------------------------------------------------------------------ */
/* firmware: the blobs embedded at build time (generated by the
 * library's scripts/gen_firmware_array.py) */

extern const uint8_t rtl8188eufw_data[];
extern const size_t rtl8188eufw_size;
extern const uint8_t rtw8189ffw_data[];
extern const size_t rtw8189ffw_size;

/* ------------------------------------------------------------------ */

static int wlan_started;

void wlan_console_ready(void);

int wlan_adapter_ready(void) {
	return wlan_started;
}

int wlan_start(void) {
	if (wlan_started) {
		return 0;
	}
	wlan_osal_cmsis_init();
	wlan_console_ready();
	/* usbdi trace stays OFF: at rx rates it floods the 115200 console
	 * (two lines per URB) and starves the wpa handshake timers. The
	 * trace is what hunted the M7 attach wild write; enable by hand
	 * (wlan_usbdi_trace_set) only when chasing a new transfer bug. */
	if (wlan_port_firmware_register("rtl8188eufw.bin", rtl8188eufw_data,
		(size_t) rtl8188eufw_size) != 0) {
		return -1;
	}
	if (wlan_port_firmware_register("rtw8189f_fw.bin", rtw8189ffw_data,
		(size_t) rtw8189ffw_size) != 0) {
		return -1;
	}
	wlan_started = 1;
	return 0;
}

/* The lwIP presentation (rx hooks + netif) needs the TCP/IP thread,
 * so it cannot happen inside wlan_start() - by then tcpip_init has
 * not run. Registered lazily: the first caller after net_start()
 * wins, everyone else no-ops. */
int wlan_lwip_start(void) {
	static int lwip_done;
	static int lwip_tried;

	if (lwip_done) {
		return 0;
	}
	if (lwip_tried) {
		return -1;
	}
	lwip_tried = 1;
	if (wlan_lwip_init() != 0) {
		return -1;
	}
	lwip_done = 1;
	return 0;
}
