#!/bin/sh
# Clean-room gate: fail if vendor traces or non-permissive licenses appear.
#
# Trace scan excludes third-party/ (vendored upstream, byte-identical) and
# docs/ (prose may explain provenance). See docs/clean-room.md in the parent
# workspace for the authoritative rule set.

set -u

fail=0

say_ok()   { printf '  ok    %s\n' "$1"; }
say_fail() { printf '  FAIL  %s\n' "$1"; fail=1; }

printf 'cleanroom-scan\n'

# --- 1. Vendor trace identifiers ------------------------------------------
# The scan script itself is excluded: it necessarily contains the vendor
# tokens, as data, and `git grep` would otherwise always match its own pattern
# list and fail every run.
#
# Whole-file-port exception list (decision D20 route, each entry backed by an
# imports.md registration). A whole-file port keeps its upstream file intact -
# identifiers included - and the BSD-3 license requires the original copyright
# header to stay. Rewriting those names would turn a faithful import into an
# unreviewable mutation of proven code. Everything NOT on this list is held to
# the zero-trace rule: new code never takes a vendor identifier.
TRACE_ALLOWED_FILES='
port/adapters/sdmmc/sdmmc_host_dwmmc.c
port/adapters/sdmmc/sdmmc_host_dwmshc.c
port/adapters/sdmmc/sdmmc_board.h
port/adapters/sdmmc/shadow/fsl_common.h
'
raw_traces=$(git grep -nIE \
  'phytium|Phytium|PHYTIUM|fparameters|fgic|FCache|FT_DEBUG|FT_[A-Z]|fdwgmac|fdwi2c|fdwmmc|fdwmshc|fdwpcie|fsata|fdsfc|fsdif|fxmac|fgmac|fpl011|f16550' \
  -- . ':!third-party' ':!docs' ':!.zcode' ':!tools/cleanroom-scan.sh' 2>/dev/null)

# POSIX-sh filter: split the raw hits into allowlisted and actionable.
traces=$(printf '%s\n' "$raw_traces" | awk -v allowed="$TRACE_ALLOWED_FILES" '
    BEGIN { n = split(allowed, a, "\n"); for (i = 1; i <= n; i++) allow[a[i]] = 1 }
    { file = $0; sub(/:.*/, "", file); if (!(file in allow)) print }')
allowed_traces=$(printf '%s\n' "$raw_traces" | awk -v allowed="$TRACE_ALLOWED_FILES" '
    BEGIN { n = split(allowed, a, "\n"); for (i = 1; i <= n; i++) allow[a[i]] = 1 }
    { file = $0; sub(/:.*/, "", file); if (file in allow) print file }' |
    sort -u | sed 's/^/        /')
if [ -n "$allowed_traces" ]; then
    printf '  note  whole-file-port exceptions (D20, registered in imports.md):\n'
    printf '%s\n' "$allowed_traces"
fi
if [ -z "$traces" ]; then
    say_ok 'vendor trace scan (expect empty)'
else
    say_fail 'vendor trace scan found:'
    printf '%s\n' "$traces"
fi

# --- 2. Vendor-style filenames --------------------------------------------
# The 'f<lowercase>' pattern also matches innocent names (fifo.c, flash.c);
# review any hit by hand rather than assuming a false positive.
# build/ and _baseline/ are generated/archived output, not sources: scanning
# them reports objects and backup images, not code we wrote.
#
# Three names are reviewed and allowed (docs/clean-room.md §5.2):
#   ffconf.h   - the name FatFs includes by name ("ffconf.h"); the file lives
#                in the adapter because upstream's own copy would shadow it.
#   fs.h       - project interface header (include/fs.h): the file system
#                interface, same vocabulary as shell.h and net.h.
#   fs_stub.c  - the K4 stub for that interface, named after it.
#   fatfs_*.{c,h} - the FatFs adapter files, named after the component the way
#                port/adapters/lwip/* is named after lwIP.
#   fsl_*.{c,h} (shadow/) - the names the vendored fsl_sdmmc protocol layer
#                includes by name; they shadow NXP SDK headers, not vendor
#                traces of ours (fsl_ is NXP's prefix, clean-room.md §3.1
#                already admits the fsl_sdmmc stack by that name).
#   fw_rtl8188eufw.c fw_rtw8189ffw.c fw_iwlwifi7260.c - the libbsd
#                adapter's firmware arrays ("fw" = firmware blob),
#                generated by the library's scripts/gen_firmware_array.py
#                (fw_iwlwifi7260.c reviewed 2026-09-26 with the PCIe line,
#                same shape as the Realtek two).
#   firmware_cmsis.c firmload.h fcntl.h (libbsd feat) - innocent
#                'f<lowercase>' words: "firmware" (the adapter's
#                firmload(9) registry + the NetBSD header it implements)
#                and "fcntl" (the POSIX header the usb device paths
#                include). Reviewed 2026-09-25, no vendor traces.
#   finsh.h (netutils feat) - the RT-Thread shell header the vendored
#                netutils code includes by name ("finsh"); it is a shim
#                shadow, not a vendor trace of ours. Reviewed 2026-09-25.
# Anything else matching the pattern is still a failure.
ALLOWED_NAMES='ffconf.h fs.h fs_stub.c fsl_common.h fsl_os_abstraction.h fsl_sdmmc_host.h fsl_sdmmc.h finterrupt.h fw_rtl8188eufw.c fw_rtw8189ffw.c fw_iwlwifi7260.c firmware_cmsis.c firmload.h fcntl.h finsh.h'
ALLOWED_PATTERNS='port/adapters/fatfs/fatfs_*.c port/adapters/fatfs/fatfs_*.h'

badnames=$(find . -path ./third-party -prune -o -path ./.git -prune -o \
  -path ./build -prune -o -path ./_baseline -prune -o \
  -type f \( -name 'f[a-z]*.c' -o -name 'f[a-z]*.h' -o -name 'f[a-z]*.S' \) -print 2>/dev/null)

hits=''
allowed=''
for name in $badnames; do
    ok=0
    for allowed_name in $ALLOWED_NAMES; do
        [ "$(basename "$name")" = "$allowed_name" ] && ok=1
    done
    for pattern in $ALLOWED_PATTERNS; do
        case "$name" in ./$pattern) ok=1 ;; esac
    done
    if [ "$ok" -eq 1 ]; then
        allowed="$allowed $name"
    else
        hits="$hits
$name"
    fi
done

if [ -n "$allowed" ]; then
    printf '  note  filename exceptions (reviewed, allowlisted):%s\n' "$allowed"
fi
if [ -z "$hits" ]; then
    say_ok 'filename scan (expect empty)'
else
    say_fail 'filename scan found (review by hand):'
    printf '%s\n' "$hits"
fi

# --- 3. Copyleft / license -------------------------------------------------
# docs/ is excluded: prose legitimately names licenses when explaining the
# rule set. This script is excluded for the same reason as in check 1.
copyleft=$(git grep -ilE 'GNU (Lesser )?General Public License|SPDX-License-Identifier: *(L)?GPL' \
  -- . ':!third-party' ':!docs' ':!tools/cleanroom-scan.sh' 2>/dev/null)
if [ -z "$copyleft" ]; then
    say_ok 'copyleft scan (expect empty)'
else
    say_fail 'copyleft found:'
    printf '%s\n' "$copyleft"
fi

printf 'cleanroom-scan: %s\n' "$([ "$fail" -eq 0 ] && echo PASS || echo FAIL)"
exit "$fail"
